-include .env
-include .env.local

MODEL  ?= glm-5:cloud   # our preferred model ;-)
ARGS   ?=               # optional additional CLI arguments
PROMPT ?=               # optional initial prompt

ifdef QWEN
MODEL = qwen3.5:397b-cloud   # sometimes qwen is better
endif

ifneq (,$(wildcard skills/))
ARGS += --plugin-dir ./		   # if we expose our own skills
endif

ifneq (,$(wildcard ../c3/))
ARGS += --plugin-dir ../c3   # use the local C3 plugin if available
endif

all: claude

claude:
	ollama launch claude --model ${MODEL} -- $(ARGS) $(PROMPT)

resume: ARGS += --resume
resume: claude

assistant: ARGS += --agent "c3:assistant"
assistant: all

project: ARGS += --agent c3:project-manager
project: claude

manage: PROMPT = "manage the project!"
manage: project

generated-image:
	ollama run x/z-image-turbo ${PROMPT}
