-include .env
-include .env.local

MODEL  ?= glm-5:cloud   # our preferred model ;-)
ARGS   ?=               # optional additional CLI arguments
PROMPT ?=               # optional initial prompt

ifdef QWEN
MODEL = qwen3.5:397b-cloud   # sometimes qwen is better
endif

ifneq (,$(wildcard skills/))
ARGS += --plugin-dir ./		   # if we expose our own skills
endif

C3_FOLDER ?= ../c3

ifneq ($(C3_FOLDER),./)             # don't include local C3 twice
ifneq (,$(wildcard $(C3_FOLDER)))
ARGS += --plugin-dir $(C3_FOLDER)   # use the local C3 plugin if available
endif
endif

all: claude

claude:
	CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1 ollama launch claude --model ${MODEL} -- $(ARGS) $(PROMPT)

resume: ARGS += --resume
resume: claude

assistant: ARGS += --agent "c3:assistant"
assistant: all

project: ARGS += --agent c3:project-manager
project: claude

manage: PROMPT = "manage the project!"
manage: project

generated-image:
	ollama run x/z-image-turbo ${PROMPT}
