-include .env
-include .env.local

MODEL  ?= glm-5:cloud   # our preferred model ;-)
ARGS   ?=               # optional additional CLI arguments
PROMPT ?=               # optional initial prompt

all: claude

claude:
	ollama launch claude --model ${MODEL} -- $(ARGS) $(PROMPT)

resume: ARGS += --resume
resume: claude

project: ARGS += --agent c3:project-manager
project: claude

manage: PROMPT = "manage the project!"
manage: project

image-generation:
	ollama run x/z-image-turbo
