[backend.ollama]
model = "glm-5.3-flash:cloud"

[context]
storage_path = "./local/context"

[agents.directories]
c3 = "./agents"

[skills.directories]
c3 = "./skills"

[tools.make.allowed_env_vars]
run = [ "MODEL" ]

[tools.git]
auto_permission = [
  "status", "log", "diff", "branch", "show", "commit", "add", "checkout", "tag"
]

[tools.github]
allowed_operations = [
  "repo_view",
  "issue_list", "issue_view", "issue_create",
  "workflow_list", "workflow_view", "workflow_logs",
  "release_create", "release_list", "release_view",
  "pr_list", "pr_view",
  "pr_reviews", "pr_comments",
  "pr_create", "pr_comment", "pr_ready", "pr_edit"
]

[tools.read]
max_file_size_kb = 750
